api = "0.7"

[buildpack]
  homepage = "https://www.runway.horse/docs/recipes/javascript/"
  id = "runway-buildpacks/nodejs"
  name = "Paketo Buildpack for Node.js"
  version = "9.3.23"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/nodejs/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "7.12.2"

  [[order.group]]
    id = "paketo-buildpacks/yarn"
    version = "2.2.12"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "2.6.12"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "2.3.12"

  [[order.group]]
    id = "paketo-buildpacks/node-start"
    optional = true
    version = "2.5.12"

  [[order.group]]
    id = "paketo-buildpacks/yarn-start"
    optional = true
    version = "2.4.11"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.4"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.4"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.3"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "7.12.2"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    version = "2.2.5"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "2.3.12"

  [[order.group]]
    id = "paketo-buildpacks/node-start"
    optional = true
    version = "2.5.12"

  [[order.group]]
    id = "paketo-buildpacks/npm-start"
    optional = true
    version = "2.3.11"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.4"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.4"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.3"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "7.12.2"

  [[order.group]]
    id = "paketo-buildpacks/node-start"
    version = "2.5.12"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.4"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.4"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.3"
