api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack with an order definition suitable for Java native image applications"
  homepage = "https://www.runway.horse/docs/recipes/java/"
  id = "runway-buildpacks/java-native-image"
  keywords = ["java", "composite", "native-image"]
  name = "Buildpack for Java Native Image"
  version = "11.15.40"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/java/blob/main/LICENSE"

[metadata]
  include-files = ["README.md", "buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/upx"
    optional = true
    version = "3.9.0"

  [[order.group]]
    id = "paketo-buildpacks/bellsoft-liberica"
    version = "11.5.3"

  [[order.group]]
    id = "paketo-buildpacks/syft"
    optional = true
    version = "2.29.0"

  [[order.group]]
    id = "paketo-buildpacks/leiningen"
    optional = true
    version = "4.14.0"

  [[order.group]]
    id = "paketo-buildpacks/gradle"
    optional = true
    version = "8.2.1"

  [[order.group]]
    id = "paketo-buildpacks/maven"
    optional = true
    version = "6.21.1"

  [[order.group]]
    id = "paketo-buildpacks/sbt"
    optional = true
    version = "6.21.1"

  [[order.group]]
    id = "paketo-buildpacks/executable-jar"
    optional = true
    version = "6.14.0"

  [[order.group]]
    id = "paketo-buildpacks/spring-boot"
    optional = true
    version = "5.35.1"

  [[order.group]]
    id = "paketo-buildpacks/datadog"
    optional = true
    version = "6.5.2"

  [[order.group]]
    id = "paketo-buildpacks/native-image"
    version = "5.17.0"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.12.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.10.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.11.0"
