api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack with an order definition suitable for Java applications"
  homepage = "https://www.runway.horse/docs/recipes/java/"
  id = "runway-buildpacks/java"
  keywords = ["java", "composite"]
  name = "Buildpack for Java"
  version = "18.12.56"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/java/blob/main/LICENSE"

[metadata]
  include-files = ["README.md", "buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/bellsoft-liberica"
    version = "11.5.1"

  [[order.group]]
    id = "paketo-buildpacks/yarn"
    optional = true
    version = "2.2.17"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true
    version = "8.0.1"

  [[order.group]]
    id = "paketo-buildpacks/syft"
    optional = true
    version = "2.28.1"

  [[order.group]]
    id = "paketo-buildpacks/leiningen"
    optional = true
    version = "4.14.0"

  [[order.group]]
    id = "paketo-buildpacks/clojure-tools"
    optional = true
    version = "2.16.0"

  [[order.group]]
    id = "paketo-buildpacks/gradle"
    optional = true
    version = "8.2.0"

  [[order.group]]
    id = "paketo-buildpacks/maven"
    optional = true
    version = "6.21.1"

  [[order.group]]
    id = "paketo-buildpacks/sbt"
    optional = true
    version = "6.21.0"

  [[order.group]]
    id = "paketo-buildpacks/executable-jar"
    optional = true
    version = "6.14.0"

  [[order.group]]
    id = "paketo-buildpacks/apache-tomcat"
    optional = true
    version = "8.8.0"

  [[order.group]]
    id = "paketo-buildpacks/apache-tomee"
    optional = true
    version = "1.16.1"

  [[order.group]]
    id = "paketo-buildpacks/liberty"
    optional = true
    version = "5.2.0"

  [[order.group]]
    id = "paketo-buildpacks/dist-zip"
    optional = true
    version = "5.11.0"

  [[order.group]]
    id = "paketo-buildpacks/spring-boot"
    optional = true
    version = "5.35.0"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.12.0"

  [[order.group]]
    id = "paketo-buildpacks/jattach"
    optional = true
    version = "1.11.0"

  [[order.group]]
    id = "paketo-buildpacks/datadog"
    optional = true
    version = "6.5.1"

  [[order.group]]
    id = "paketo-buildpacks/java-memory-assistant"
    optional = true
    version = "1.9.0"

  [[order.group]]
    id = "paketo-buildpacks/encrypt-at-rest"
    optional = true
    version = "4.10.1"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.10.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.11.0"
