api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/php"
  id = "runway-buildpacks/php"
  name = "Buildpack for PHP"
  version = "2.19.27"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/php/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = "2.3.39"

  [[order.group]]
    id = "paketo-buildpacks/composer"
    optional = true
    version = "0.7.16"

  [[order.group]]
    id = "paketo-buildpacks/composer-install"
    optional = true
    version = "0.3.28"

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = "1.0.2"

  [[order.group]]
    id = "paketo-buildpacks/php-fpm"
    version = "0.2.46"

  [[order.group]]
    id = "paketo-buildpacks/php-httpd"
    version = "0.3.44"

  [[order.group]]
    id = "paketo-buildpacks/php-memcached-session-handler"
    optional = true
    version = "0.2.32"

  [[order.group]]
    id = "paketo-buildpacks/php-redis-session-handler"
    optional = true
    version = "0.2.41"

  [[order.group]]
    id = "paketo-buildpacks/php-start"
    version = "0.4.46"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.12.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.10.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.11.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = "2.3.39"

  [[order.group]]
    id = "paketo-buildpacks/composer"
    optional = true
    version = "0.7.16"

  [[order.group]]
    id = "paketo-buildpacks/composer-install"
    optional = true
    version = "0.3.28"

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "1.0.7"

  [[order.group]]
    id = "paketo-buildpacks/php-fpm"
    version = "0.2.46"

  [[order.group]]
    id = "paketo-buildpacks/php-nginx"
    version = "0.3.29"

  [[order.group]]
    id = "paketo-buildpacks/php-memcached-session-handler"
    optional = true
    version = "0.2.32"

  [[order.group]]
    id = "paketo-buildpacks/php-redis-session-handler"
    optional = true
    version = "0.2.41"

  [[order.group]]
    id = "paketo-buildpacks/php-start"
    version = "0.4.46"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.12.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.10.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.11.0"
