api = "0.7"

[buildpack]
  id = "runway-buildpacks/runway"
  name = "Composite buildpack to include our own buildpacks"
  version = "0.1.27"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    optional = true
    version = "2.9.10"

  [[order.group]]
    id = "paketo-buildpacks/git"
    optional = true
    version = "1.1.11"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true
    version = "7.12.2"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    optional = true
    version = "2.2.5"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "2.3.12"

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    optional = true
    version = "1.0.5"

  [[order.group]]
    id = "runway-buildpacks/static-websites"
    version = "0.4.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    optional = true
    version = "2.9.10"

  [[order.group]]
    id = "paketo-buildpacks/git"
    optional = true
    version = "1.1.11"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true
    version = "7.12.2"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    optional = true
    version = "2.2.5"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "2.3.12"

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    optional = true
    version = "1.0.1"

  [[order.group]]
    id = "runway-buildpacks/static-websites"
    version = "0.4.0"
