api = "0.7"

[buildpack]
  id = "runway-buildpacks/runway"
  name = "Buildpack for hugo/mdbook"
  version = "0.1.30"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    optional = true
    version = "2.9.13"

  [[order.group]]
    id = "paketo-buildpacks/git"
    optional = true
    version = "1.1.15"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true
    version = "7.13.2"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    optional = true
    version = "2.2.8"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "2.3.16"

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    optional = true
    version = "1.0.8"

  [[order.group]]
    id = "runway-buildpacks/static-websites"
    version = "0.4.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    optional = true
    version = "2.9.13"

  [[order.group]]
    id = "paketo-buildpacks/git"
    optional = true
    version = "1.1.15"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true
    version = "7.13.2"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    optional = true
    version = "2.2.8"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "2.3.16"

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    optional = true
    version = "1.0.2"

  [[order.group]]
    id = "runway-buildpacks/static-websites"
    version = "0.4.0"
