api = "0.7"

[buildpack]
  id = "runway-buildpacks/runway"
  name = "Composite buildpack to include our own buildpacks"
  version = "0.1.20"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    optional = true
    version = "2.9.5"

  [[order.group]]
    id = "paketo-buildpacks/git"
    optional = true
    version = "1.1.7"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true
    version = "7.11.0"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    optional = true
    version = "2.2.2"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "2.3.8"

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    optional = true
    version = "1.0.2"

  [[order.group]]
    id = "runway-buildpacks/static-websites"
    version = "0.4.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    optional = true
    version = "2.9.5"

  [[order.group]]
    id = "paketo-buildpacks/git"
    optional = true
    version = "1.1.7"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true
    version = "7.11.0"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    optional = true
    version = "2.2.2"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "2.3.8"

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    optional = true
    version = "0.7.72"

  [[order.group]]
    id = "runway-buildpacks/static-websites"
    version = "0.4.0"
