api = "0.7"

[buildpack]
  description = "A buildpack for building Go applications"
  homepage = "https://www.runway.horse/docs/recipes/deploy-go/"
  id = "runway-buildpacks/go"
  keywords = ["go", "golang"]
  name = "Runway version of the Paketo Buildpack for Go"
  version = "4.13.28"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/go/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "2.9.7"

  [[order.group]]
    id = "paketo-buildpacks/git"
    optional = true
    version = "1.1.8"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true
    version = "7.11.1"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    optional = true
    version = "2.2.3"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "2.3.9"

  [[order.group]]
    id = "paketo-buildpacks/go-mod-vendor"
    version = "1.1.7"

  [[order.group]]
    id = "paketo-community/go-generate"
    optional = true
    version = "0.3.28"

  [[order.group]]
    id = "paketo-buildpacks/go-build"
    version = "2.4.5"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.4"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.4"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.3"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "2.9.7"

  [[order.group]]
    id = "paketo-buildpacks/git"
    optional = true
    version = "1.1.8"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true
    version = "7.11.1"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    optional = true
    version = "2.2.3"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "2.3.9"

  [[order.group]]
    id = "paketo-community/go-generate"
    optional = true
    version = "0.3.28"

  [[order.group]]
    id = "paketo-buildpacks/go-build"
    version = "2.4.5"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.4"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.4"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.3"
